### ISSUE TITLE
Clarify reselect migration usage

### ISSUE THREAD

**Issue by oyeanuj** [josepot/redux-views#23]
Hi @josepot, thank you for creating this library! As I migrate from Reselect, I wasn't sure if this part was a typo or if `createSelector` does not require array input:

```js
createSelector(
  getRunningCars,
  (_, props) => props.carId,
  (cars, carId) => cars[props.carId]
);
```
becomes
```js
const getCarIdProp = createIdSelector(props => props.carId);

createSelector(
  getRunningCars,
  getCarIdProp,
  (cars, carId) => cars[props.carId]
);
```

Should the last method instead be:

```diff
createSelector(
+ [
  getRunningCars,
  getCarIdProp,
+ ],
  (cars, carId) => cars[props.carId]
);
```

**Comment by josepot** [comment]
Hi @oyeanuj 

Sorry for the late response... I just saw this.

Yes, it does require an array input as [it's explained in the following section of the README](https://github.com/josepot/redux-views#migrating-from-reselect40).

> This version of redux-views removes the variadic overload of createSelector from reselect@4.0, which means that all calls that were using this overload will need to be changed. 

The reason for this change is that it made the typings a lot better an easier.

Please let me know if this answer your question. Also, if you think that the docs could be improved, PRs are more than welcomed :wink:  

Oh, I guess that it was a typo, but the selector should become like this with redux-views:
```js
createSelector(
+ [
  getRunningCars,
  getCarIdProp,
+ ],
  (cars, carId) => cars[carId] // you had `props.carId`. I guess that was a typo
);
```
